"""users_added_is_archived_value

Revision ID: 4fa506ea993b
Revises: 6885e1726407
Create Date: 2026-09-27 10:41:02.486993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fa506ea993b'
down_revision: Union[str, Sequence[str], None] = '6885e1726407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_archived', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.alter_column('users', 'is_archived', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_archived')
    # ### end Alembic commands ###
